import { NextRequest, NextResponse } from 'next/server';
import { courseStore } from '@/lib/courseStore';

// Mock function to simulate Jam content extraction
async function extractJamContent(jamUrl: string) {
  // In a real implementation, this would:
  // 1. Parse the Jam URL to extract the Jam ID
  // 2. Call Nullshot API or scrape the public Jam page
  // 3. Extract conversation history, prompts, and metadata
  
  // For demo purposes, return mock data
  return {
    id: 'mock-jam-' + Date.now(),
    title: 'Custom Todo App',
    description: 'Building a todo application with custom features',
    conversation: [
      { role: 'user', content: 'I want to build a todo app' },
      { role: 'assistant', content: 'I\'ll help you create a todo app with React...' },
      // ... more conversation
    ],
    prompts: [
      'Create a new React component for todo items',
      'Add state management for the todo list',
      'Implement add, edit, and delete functionality',
      'Style the app with Tailwind CSS'
    ],
    techStack: ['React', 'TypeScript', 'Tailwind'],
    difficulty: 'beginner',
    metadata: {
      duration: '60 min',
      steps: 6
    }
  };
}

// Mock function to generate tutorial from Jam content
async function generateTutorial(jamContent: any) {
  // In a real implementation, this would:
  // 1. Send the Jam content to an AI service (OpenAI, Claude, etc.)
  // 2. Generate structured tutorial steps
  // 3. Create code examples and explanations
  
  return {
    overview: `Learn to build ${jamContent.title} step by step. This tutorial covers the fundamentals of React development including component creation, state management, and styling.`,
    steps: [
      {
        id: 1,
        title: 'Project Setup',
        description: 'Initialize the project and install dependencies',
        code: 'npx create-react-app todo-app --template typescript',
        explanation: 'We start with a TypeScript React template for better development experience.'
      },
      {
        id: 2,
        title: 'Create Todo Component',
        description: 'Build the main todo list component',
        code: `interface Todo {
  id: string;
  text: string;
  completed: boolean;
}

function TodoList() {
  const [todos, setTodos] = useState<Todo[]>([]);
  // ... component logic
}`,
        explanation: 'Define the Todo interface and create the main component with state management.'
      }
      // ... more steps would be generated by AI
    ]
  };
}

// Mock function to generate quiz questions
async function generateQuiz(jamContent: any, tutorial: any) {
  // In a real implementation, this would generate quiz questions based on the tutorial content
  
  return [
    {
      id: 1,
      question: 'What React hook is used for managing component state?',
      options: ['useEffect', 'useState', 'useContext', 'useReducer'],
      correctAnswer: 1,
      explanation: 'useState is the primary hook for managing local component state in React functional components.'
    },
    {
      id: 2,
      question: 'Why is TypeScript beneficial in React development?',
      options: [
        'It makes the code run faster',
        'It provides type safety and better IDE support',
        'It reduces bundle size',
        'It\'s required for React'
      ],
      correctAnswer: 1,
      explanation: 'TypeScript provides compile-time type checking and enhanced IDE features like autocomplete and refactoring.'
    }
  ];
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as { jamUrl: string };
    const jamUrl = body.jamUrl;

    if (!jamUrl) {
      return NextResponse.json(
        { error: 'Jam URL is required' },
        { status: 400 }
      );
    }

    // Validate URL format (basic check)
    if (!jamUrl.includes('jam.nullshot.dev') && !jamUrl.includes('nullshot.dev')) {
      return NextResponse.json(
        { error: 'Invalid Jam URL format' },
        { status: 400 }
      );
    }

    // Step 1: Extract Jam content
    console.log('Extracting Jam content from:', jamUrl);
    const jamContent = await extractJamContent(jamUrl);

    // Step 2: Generate tutorial
    console.log('Generating tutorial...');
    const tutorial = await generateTutorial(jamContent);

    // Step 3: Generate quiz
    console.log('Generating quiz...');
    const quiz = await generateQuiz(jamContent, tutorial);

    // Step 4: Create course object
    const course = {
      id: jamContent.id,
      title: jamContent.title,
      description: jamContent.description,
      difficulty: jamContent.difficulty as 'beginner' | 'intermediate' | 'advanced',
      techStack: jamContent.techStack,
      jamUrl: jamUrl,
      duration: jamContent.metadata.duration,
      overview: tutorial.overview,
      steps: tutorial.steps,
      quiz: quiz,
      appUrl: `https://demo.nullshot.dev/${jamContent.id}`, // Mock demo URL
      createdAt: new Date().toISOString()
    };

    // Save the course to our store
    courseStore.addCourse(course);
    console.log('Course generated and saved:', course.title);

    return NextResponse.json({
      success: true,
      course: course,
      message: 'Tutorial generated successfully!'
    });

  } catch (error) {
    console.error('Error processing Jam:', error);
    return NextResponse.json(
      { error: 'Failed to process Jam. Please try again.' },
      { status: 500 }
    );
  }
}





